//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DOCTOREntities : DbContext
    {
        public DOCTOREntities()
            : base("name=DOCTOREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_DOCTOR> TB_DOCTOR { get; set; }
        public virtual DbSet<TB_PARAMETERS> TB_PARAMETERS { get; set; }
        public virtual DbSet<TB_SPECIALITY> TB_SPECIALITY { get; set; }
        public virtual DbSet<TB_USERS> TB_USERS { get; set; }
    
        public virtual ObjectResult<SP_GET_SEARCH_DOCTOR_Result> SP_GET_SEARCH_DOCTOR(string doctorName, string speciality)
        {
            var doctorNameParameter = doctorName != null ?
                new ObjectParameter("DoctorName", doctorName) :
                new ObjectParameter("DoctorName", typeof(string));
    
            var specialityParameter = speciality != null ?
                new ObjectParameter("Speciality", speciality) :
                new ObjectParameter("Speciality", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_SEARCH_DOCTOR_Result>("SP_GET_SEARCH_DOCTOR", doctorNameParameter, specialityParameter);
        }
    }
}
