//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DOCTOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_DOCTOR()
        {
            this.TB_SPECIALITY = new HashSet<TB_SPECIALITY>();
        }
    
        public int ID_DOCTOR { get; set; }
        public string DOCTORNAME { get; set; }
        public System.DateTime BORNDATE { get; set; }
        public string LOCATIONDOCTOR { get; set; }
        public string DESCRIPTION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_SPECIALITY> TB_SPECIALITY { get; set; }
    }
}
