//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PARAMETERS
    {
        public int ID_PARAM { get; set; }
        public string DESCR_PARAM { get; set; }
        public string VAL1 { get; set; }
        public string VAL2 { get; set; }
        public string VAL3 { get; set; }
    }
}
