//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SPECIALITY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_SPECIALITY()
        {
            this.TB_DOCTOR = new HashSet<TB_DOCTOR>();
        }
    
        public int ID_SPECIALITY { get; set; }
        public string DESCR_SPECIALITY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_DOCTOR> TB_DOCTOR { get; set; }
    }
}
