//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USERS
    {
        public int ID_USER { get; set; }
        public string USERNAME { get; set; }
        public string USERPASSWORD { get; set; }
        public System.DateTime BORNDATE { get; set; }
        public string USEREMAIL { get; set; }
    }
}
